name: Build dotnet

on:
  pull_request:
    branches:
      - main

jobs:
  run-buld:
    runs-on: ${{matrix.os}}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        
      - name: Run build
        run: dotnet build
        
      - name: Run test
        if: success()
        run: dotnet test

      - name: Run Node
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      #- name: Install_Dependecies
        #run:  


